version: '3.8'
services:
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"   # Kafka port
      - "9093:9093"   # Kafka port
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  backend-producer:
    build:
      context: ./backend-producer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"   # Backend producer port
    depends_on:
      - kafka

  backend-consumer:
    build:
      context: ./backend-consumer
      dockerfile: Dockerfile
    ports:
      - "3001:3001"   # Backend consumer port
    depends_on:
      - kafka

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"   # React frontend port
    depends_on:
      - backend-producer
      - backend-consumer

